### PR TITLE
Fixed to enable OSX building

### PR DESCRIPTION
**Pull request by shybovycha**
During build on OSX there were next compile-time errors:

1. `use of undeclared identifier 'CLOCK_REALTIME'`

  That was caused by the fact that `_MACOSX_VER` constant was not defined anywhere

2.  `error: constant expression evaluates to 16945909448695747420 which cannot be narrowed to type 'long long' [-Wc++11-narrowing]`

  Here compiler suggested adding static type casting. I suggest that's the better option than turning compiler flag off

3. `error: redefinition of 'baseCount'`. This is because OSX is a Unix system as well, so the 

  `#if (defined (_POSIX_VER) || defined (_POSIX_VER_64))` condition works too and, when used in a separate `#if` condition, re-defines some of the variables.

This pull request fixes all of those errors so it is now possible to build Newton GD on OSX.

### CODE REVIEW

**Comment by JulioJerez** [comment]
I am looking at the request, this is a year old 
is unlike is still valid.
can you verified this please.

**Comment by shybovycha** [comment]
The first thing I saw right after running `take build && cmake .. && make` was:

```
coreLibrary_300/source/core/dgVector.h:1392:10: error: 
      use of undeclared identifier '_mm_floor_ps'
                return _mm_floor_ps(m_type);
```

Digging deeper, I've found there is no `_MACOSX_VER` flag being defined. So I've added a small workaround in `dgTypes.h`:

```
#ifdef __APPLE__
	#define _MACOSX_VER
#endif
```

But the problem remained. So I've moved the `#include <smmintrin.h>` out of the `#ifdef __SSE4_1__` instruction to force its include.

Now, OSX is a Posix-compatible system. And both `#if (defined (_POSIX_VER) || defined (_POSIX_VER_64))` and `#ifdef _MACOSX_VER` do pass, so there was an error in `dgTypes.cpp`:

```
coreLibrary_300/source/core/dgTypes.cpp:65:22: error: 
      redefinition of 'baseCount'
        static dgUnsigned64 baseCount = 0;
                            ^
coreLibrary_300/source/core/dgTypes.cpp:53:22: note: 
      previous definition is here
        static dgUnsigned64 baseCount = 0;
```

So I've merged those declarations:

```
#if (defined (_POSIX_VER) || defined (_POSIX_VER_64))
    #ifndef _MACOSX_VER
...
    #else
...
    #endif
#endif
```

And now I am only seeing this error *(and can do nothing about it :disappointed: )*

```
coreLibrary_300/source/core/dgVector.h:1392:10: error: 
      '__builtin_ia32_roundps' needs target feature sse4.1
                return _mm_floor_ps(m_type);
```

**Comment by JulioJerez** [comment]
yes, I was adding double precision support and I saw that function which is better than the emulation that I had, but I did not realized it was a SSE4.1 functionality. 
I fixed now, sorry about that,

I just update the xcode OSX project, it soudl all be working now.

**Comment by shybovycha** [comment]
Now the library itself builds successfully, just with a small fix - I've reworked the `#ifdef` a bit to be more "convention correct".

Yet, the `demoSandbox` project fails to build *(at least in my current macbook setup :yum: )*. But that's the thing of another pull request, right?

**Comment by shybovycha** [comment]
Yeah, and just remembered the webpage, our lecturer recommended us when we talked about SSE: [Intel Intrinsincs Guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide/) - there are all the MMX/SSE functions listed there, and nicely split onto categories *(SSE versions and tasks)*. Could be handy

**Comment by JulioJerez** [comment]
this was fix alredy

**Pull request closed without merging**
