### PR TITLE
dCustomHingeActuator: Remove "tol" variable causing the actuator to show jerky movements at slow speeds.

### PR DESCRIPTION
**Pull request by TrevorCash**

### CODE REVIEW

**Comment by JulioJerez** [comment]
Ok I merged for now but I do not think is a good fix. 
I do see there is a bug with the joint, basically when target is outside the tolerance it will move with the actuator speed and that ok because it will not overshoot, 
but when is inside is to range it does nothing and that can be a problem, 
the proper fix is not to remove the tolerance, but to add the third branch the use small angular displacement to reach the target.
removing the tol will also produce jitters by overshooting, did you get that.    
I will try to fix it tonight

**Comment by TrevorCash** [comment]
Yes I see what your saying - if the current angle is within the "tolerance zone" the speed could be based on a fraction of the current error.  This is the behavior I was seeing with the original code: https://youtu.be/MSvYxOJRy_I

**Comment by JulioJerez** [comment]
in the video, is that how was behaving before you made the change?
it certainly look wrong.
I did not have time to look at it, I try to check it out later.
it is dearly intuitive to make changes to the joints, it is essentially one dimetional dynamics. I am glad you are looking at it, not too many people do.
instead they set something and the moment they see something they do not expect the assume the engine is as erroneous as some of the pupolar others
and that's just a false equivalence.
there are degrees of wrongness.
with newton those thing are high level implemention detail that feed wrong data to the solver, with some engine the result is wrong even with the wright data, and those are very different things.

**Comment by JulioJerez** [comment]
hold to that test case so that when I made the fix you try again please.

**Comment by JulioJerez** [comment]
Ok you where right teh tolerance made no sence, that was a legacy form older code.
there is not need for a dead zone, the speed is already clipped inside the if  statement.
the tol was just a bad bug. I fix the oeth actuators as well.
on the actuator acting more liek real life,  you are probably referring to PID style of actuators.
whi basicall take teh oputpoi of teh system, and apply a feedback proportion to the error the error speed, and the error accumulation. 

those systems are still in use today but but more for analg systems. 
today more and more actuator use step Motors specially for small system.

if you wna to make  a PID style actuator,  you by subclassing  form the hinge and intead of calculation the acceleration  calculaate the PID torque as added to the two connected bodies.

that the flexibility of the dCustom Jopint system, once you undertand eassilly make a model of almos any mechanical system be decrete or analog.

I do not recoment the use of PID believe me, that rout set you to moth and moth of tunning parametsr by tril an error.  and usiaully when you think you got it tune, the when you go to use it, any imput to the system causes a huge oscillations of the entire contraction  and ther you back again to calibration.

this is how many engines do Ragdolls, vehicle and other articulate joint using the Featherstone  algorithm, Newton has a more general solver that alows for motors to be part of the joint solver, therefore is can calculate presize torque of forces.
This is why I keep saying not all engines are created equal, some errors are more wrong than others. 
and people  who make thes naive comparison simple make the fallacy of false equivalience, 
they equate having inplemenation of a end featore with fundamental ways of opertaions as if boteh equat to the same bug.

I set the forklift demo as default for now because it shows all the actuators in actions.
anyway it all should be update now.

**Comment by TrevorCash** [comment]
Ok good to know I wasn't too crazy with seeing that.

**Pull request merged**
